#!/usr/bin/env python

from time import sleep

COMPILE_COFFEE = False


def shell(cmd, ps):
    from subprocess import Popen
    print '+ $', cmd,
    p = Popen(cmd, shell=True)
    print '[PID %d]' % p.pid
    ps.append(p)


def server():
    import sys
    oldsetting = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    import server
    sys.dont_write_bytecode = oldsetting
    print '+ >>>', 'server.server()'
    server.server()


def main():
    try:
        ps = []
        shell('sass --watch ./src/sass/style.sass:./assets/styles/style.css', ps)
        shell('jade --watch -o ./views ./src/jade', ps)
        if COMPILE_COFFEE:
            shell('coffee --watch --output ./assets/scripts --compile ./src/coffee/main.coffee', ps)
        server()
    except KeyboardInterrupt:
        pass
    finally:
        print
        print 'Sending all processes the TERM signal...'
        for p in ps: p.terminate()
        sleep(0.3)
        print 'Sending all processes the KILL signal...'
        for p in ps: p.kill()
        print 'Server stopped.'

if __name__ == '__main__':
    main()
