// Generated by CoffeeScript 1.7.1
(function() {
  var LiveDJ;

  LiveDJ = (function() {
    var self;
    self = {};
    self.roomName = void 0;
    self.currentSongData = void 0;
    self.lastTrackURL = void 0;
    self.httpGet = function(theUrl) {
      var xmlHttp;
      xmlHttp = null;
      xmlHttp = new XMLHttpRequest();
      xmlHttp.open('GET', theUrl, false);
      xmlHttp.send(null);
      return xmlHttp.responseText;
    };
    self.search = function(query) {
      var res, response;
      response = self.httpGet('http://ws.spotify.com/search/1/track.json?q=' + query);
      res = JSON.parse(response);
      if (res.tracks[0]) {
        return res.tracks[0].href;
      }
    };
    self.updatePicture = function() {
      var response, trackID;
      trackID = self.lastTrackURL;
      response = $.getJSON('https://embed.spotify.com/oembed/?url=' + trackID + '&callback=?', function(data) {
        var albumTitle, bigImage;
        console.log(response);
        bigImage = data.thumbnail_url.replace(/\/cover\//, '/640/');
        $('#albumimage').attr('src', bigImage);
        albumTitle = document.createElement('text');
        albumTitle.innerHTML = data.title;
        console.log(albumTitle);
        $('#titleContainer').html(albumTitle);
      });
    };
    self.updateInputIfNecessary = function(selector, value) {
      var $el;
      $el = $(selector);
      if ($el.val() !== value) {
        $el.val(value);
      }
      $el.addClass('flash');
      setTimeout((function() {
        $el.removeClass('flash');
      }), 0);
    };
    self.changeRoom = function(roomName) {
      roomName = roomName.toLowerCase();
      self.currentSongData = new Firebase('https://tuneinwithme.firebaseio.com/rooms/' + roomName + '/song');
      self.currentSongData.on('value', self.onDataChange);
      self.updateInputIfNecessary('#roominput', roomName);
      console.log('room changed to ' + roomName);
    };
    self.onDataChange = function(data) {
      if (!(data && data.val())) {
        return;
      }
      self.lastInput = data.val();
      self.lastTrackURL = self.inputToTrackURL(self.lastInput);
      self.currentSongData.set((self.lastTrackURL ? self.lastTrackURL : null));
      self.updateInputIfNecessary('#songinput', self.lastTrackURL);
      self.updatePicture();
      self.changeBackground();
      console.log('Track URL updated: ', self.lastTrackURL);
    };
    self.inputToTrackURL = function(input) {
      var m;
      if (input.search(/^spotify:track:/) === 0) {
        return input;
      }
      m = input.match(/open.spotify.com\/track\/(\w+)/);
      if (m) {
        return 'spotify:track:' + m[1];
      }
      return self.search(input);
    };
    self.submitSong = function() {
      self.currentSongData.set($('#songinput').val());
      $('#songinput').select();
    };
    $('#submitSong').click(function(evt) {
      evt.preventDefault();
      return self.submitSong();
    });
    self.submitRoom = function() {
      self.changeRoom($('#roominput').val());
      $('#roominput').select();
    };
    $('#submitRoom').click(function(evt) {
      evt.preventDefault();
      return self.submitRoom();
    });
    self.init = function() {
      self.changeRoom('welcometohacktech');
      $('#songinput').select();
    };
    self.changeBackground = function() {
      var hour;
      hour = new Date().getHours();
      if (hour < 7 || hour > 18) {
        $('body').removeClass('day');
        $('body').addClass('night');
      } else {
        $('body').removeClass('night');
        $('body').addClass('day');
      }
    };
    return self;
  })();

  $(document).ready(LiveDJ.init);

}).call(this);
