// Generated by CoffeeScript 1.7.1
(function() {
  var LiveDJ,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  LiveDJ = (function() {
    var bind;

    bind = function(selector, callback) {
      return $(selector).click((function(_this) {
        return function(evt) {
          evt.preventDefault();
          return callback();
        };
      })(this));
    };

    function LiveDJ() {
      this.submitRoom = __bind(this.submitRoom, this);
      this.submitSong = __bind(this.submitSong, this);
      this.roomName = void 0;
      this.currentSongData = void 0;
      this.lastTrackURL = void 0;
      $(document).ready((function(_this) {
        return function() {
          _this.changeRoom('welcometohacktech');
          $('#songinput').select();
          bind('#submitSong', _this.submitSong);
          return bind('#submitRoom', _this.submitRoom);
        };
      })(this));
    }

    LiveDJ.prototype.httpGet = function(theUrl) {
      var xmlHttp;
      xmlHttp = null;
      xmlHttp = new XMLHttpRequest();
      xmlHttp.open('GET', theUrl, false);
      xmlHttp.send(null);
      return xmlHttp.responseText;
    };

    LiveDJ.prototype.search = function(query) {
      var res, response;
      response = this.httpGet('http://ws.spotify.com/search/1/track.json?q=' + query);
      res = JSON.parse(response);
      if (res.tracks[0]) {
        return res.tracks[0].href;
      }
    };

    LiveDJ.prototype.updatePicture = function() {
      var response, trackID;
      trackID = this.lastTrackURL;
      return response = $.getJSON('https://embed.spotify.com/oembed/?url=' + trackID + '&callback=?', function(data) {
        var albumTitle, bigImage;
        console.log(response);
        bigImage = data.thumbnail_url.replace(/\/cover\//, '/640/');
        $('#albumimage').attr('src', bigImage);
        albumTitle = document.createElement('text');
        albumTitle.innerHTML = data.title;
        console.log(albumTitle);
        return $('#titleContainer').html(albumTitle);
      });
    };

    LiveDJ.prototype.updateInputIfNecessary = function(selector, value) {
      var $el;
      $el = $(selector);
      if ($el.val() !== value) {
        $el.val(value);
      }
      $el.addClass('flash');
      return setTimeout(function() {
        return $el.removeClass('flash');
      }, 0);
    };

    LiveDJ.prototype.changeRoom = function(roomName) {
      roomName = roomName.toLowerCase();
      this.currentSongData = new Firebase('https://tuneinwithme.firebaseio.com/rooms/' + roomName + '/song');
      this.currentSongData.on('value', (function(_this) {
        return function(data) {
          if (!(data && data.val())) {
            return;
          }
          _this.lastInput = data.val();
          _this.lastTrackURL = _this.inputToTrackURL(_this.lastInput);
          _this.currentSongData.set((_this.lastTrackURL ? _this.lastTrackURL : null));
          _this.updateInputIfNecessary('#songinput', _this.lastTrackURL);
          _this.updatePicture();
          _this.changeBackground();
          return console.log('Track URL updated: ', _this.lastTrackURL);
        };
      })(this));
      this.updateInputIfNecessary('#roominput', roomName);
      return console.log('room changed to ' + roomName);
    };

    LiveDJ.prototype.inputToTrackURL = function(input) {
      var m;
      if (input.search(/^spotify:track:/) === 0) {
        return input;
      }
      m = input.match(/open.spotify.com\/track\/(\w+)/);
      if (m) {
        return 'spotify:track:' + m[1];
      }
      return this.search(input);
    };

    LiveDJ.prototype.submitSong = function() {
      this.currentSongData.set($('#songinput').val());
      return $('#songinput').select();
    };

    LiveDJ.prototype.submitRoom = function() {
      this.changeRoom($('#roominput').val());
      return $('#roominput').select();
    };

    LiveDJ.prototype.changeBackground = function() {
      var hour;
      hour = new Date().getHours();
      if (hour < 7 || hour > 18) {
        $('body').removeClass('day');
        return $('body').addClass('night');
      } else {
        $('body').removeClass('night');
        return $('body').addClass('day');
      }
    };

    return LiveDJ;

  })();

  window.LiveDJ = new LiveDJ;

}).call(this);
